log_level                :info
log_location             STDOUT
node_name                'venkat'
client_key               '/home/venkat/chef-cookbooks/.chef/venkat.pem'
validation_client_name   'chef-validator'
validation_key           '/home/venkat/chef-cookbooks/chef-validator.pem'
chef_server_url          'https://chef-server.venkat.com:443'
syntax_check_cache_path  '/root/chef-repo/.chef/syntax_check_cache'
cookbook_path		 '/home/venkat/chef-cookbooks/cookbooks'
